### ISSUE TITLE
problem ze stylami modali

### ISSUE THREAD

**Issue by kgryguc** [KlaudiaKrekora/team-project-IceCream#52]
Stylowanie modali dołączone w https://github.com/KlaudiaKrekora/team-project-IceCream/pull/49 spowodowało problemy z modalami np. w sekcji products. Proponuję cofnięcie zmian, uzgodnienie wspólnych styli modali na całej stronie i dodanie modyfikatorów w poszczególnych sekcjach. @KlaudiaKrekora @KarolTrombala @mikasaurus @DorotaDobija @JustDunia @MaciekJozwicki

**Comment by KlaudiaKrekora** [comment]
Krzysztof jestem jak najbardziej za. Niestety ostatnie zmiany mocno namieszały

**Comment by KarolTrombala** [comment]
Poprawiłem modala w about - wrzuciłem nowego brancha feature/about i modale działają
